# Generated by Django 3.2.9 on 2021-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='play_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
