# Generated by Django 3.2.9 on 2021-11-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0002_alter_game_play_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='age_recomendation',
            new_name='age_recommendation',
        ),
    ]
