# Generated by Django 3.2.9 on 2021-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0003_rename_age_recomendation_game_age_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
