# Generated by Django 3.2.9 on 2021-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0007_alter_review_game_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='game_review',
            field=models.TextField(default='cool'),
            preserve_default=False,
        ),
    ]
