# Generated by Django 3.2.9 on 2021-11-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0008_auto_20211112_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gamer_rater_api.game'),
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamer_rater_api.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamer_rater_api.player')),
            ],
        ),
    ]
