# Generated by Django 3.2.9 on 2021-11-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0009_auto_20211113_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
