# Generated by Django 3.2.9 on 2021-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_rater_api', '0011_alter_gamerating_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='average_rating',
            field=models.IntegerField(),
        ),
    ]
